// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    CardChunk: typeof import('./src/components/CardChunk/index.vue')['default']
    CurrentTime: typeof import('./src/components/MusicPlayer/compoents/CurrentTime.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    List: typeof import('./src/components/Search/List.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MusicDetail: typeof import('./src/components/MusicDetail/index.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SongInfo: typeof import('./src/components/SongInfo/index.vue')['default']
    SongList: typeof import('./src/components/SongList/index.vue')['default']
    UserDetailCard: typeof import('./src/components/UserDetailCard/index.vue')['default']
    Volume: typeof import('./src/components/MusicPlayer/compoents/Volume.vue')['default']
  }
}

export {}
