// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CurrentTime: typeof import('./src/components/MusicPlayer/compoents/CurrentTime.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MusicPlayer: typeof import('./src/components/MusicPlayer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SongInfo: typeof import('./src/components/SongInfo/index.vue')['default']
    SongList: typeof import('./src/components/SongList/index.vue')['default']
    Volume: typeof import('./src/components/MusicPlayer/compoents/Volume.vue')['default']
  }
}

export {}
